require('dotenv').config();
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const path = require('path');
const db = require('./database/database');
const products = require('./routes/products');
const categories = require('./routes/categories');
const auth = require('./routes/auth');
const orders = require('./routes/orders');
const admin = require('./routes/admin');
const reviews = require('./routes/reviews');
const { errorHandler } = require('./middleware/errorHandler');

const app = express();
const PORT = Number(process.env.PORT || 3000);
if (process.env.NODE_ENV === 'production' && (!process.env.JWT_SECRET || process.env.JWT_SECRET === 'dev-secret')) throw new Error('JWT_SECRET must be set to a strong secret in production.');
app.disable('x-powered-by');
app.use(morgan('dev'));
app.use(cors({ origin: process.env.CORS_ORIGIN && process.env.CORS_ORIGIN !== '*' ? process.env.CORS_ORIGIN.split(',').map(x => x.trim()) : true, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.get('/api/health', (req,res) => res.json({ ok:true, service:"Afia's World API" }));
app.use('/api/products', products);
app.use('/api/reviews', reviews);
app.use('/api/categories', categories);
app.use('/api/auth', auth);
app.use('/api/orders', orders);
app.use('/api/admin', admin);
app.use(express.static(path.join(__dirname, '..', 'frontend')));
app.use('/api', (req,res) => res.status(404).json({ error:'API route not found' }));
app.use((req,res) => res.sendFile(path.join(__dirname, '..', 'frontend', 'index.html')));
app.use(errorHandler);
if (require.main === module) app.listen(PORT, () => console.log(`Afia's World running at http://localhost:${PORT}`));
module.exports = app;
